# Generated by Django 4.2.6 on 2023-12-04 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admintrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='reportes',
            fields=[
                ('codigo', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='reportes')),
                ('estatus', models.CharField(default='En Proceso', max_length=50)),
                ('comentario', models.CharField(default='sin comentarios', max_length=200)),
                ('usuario_correo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portalWeb.usuario')),
            ],
        ),
    ]
